version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        # This loads the credentials from your .env file into the container
        env_file:
            - .env